version: '3.3'

services:
    hunter:
        image: japt/hunter
        ports:
            - '8080:8080'
            - '8443:8443'
        depends_on:
            - db
        environment:
          SPRING_PROFILES_ACTIVE: test
        restart: always
    db:
      image: postgres
      restart: always
      environment:
          POSTGRES_PASSWORD: example
